ci(solano): fix yarn upgrade

diff --git a/solano.yml b/solano.yml
--- a/solano.yml
+++ b/solano.yml
@@ -7,7 +7,16 @@ environment:
 
 hooks:
   pre_setup: |
-    sudo npm i -g yarn@^1.0.0
+    set -o errexit -o pipefail  # Exit on error
+    # Install yarn if it isn't already present
+    if [ ! -d $HOME/.yarn ]; then
+      wget https://yarnpkg.com/install.sh -O $TMPDIR/yarn-install.sh
+      chmod +x $TMPDIR/yarn-install.sh
+      $TMPDIR/yarn-install.sh --version 1.5.1
+    fi
+    mkdir -p $HOME/bin  # Automatically in $PATH on workers
+    ln -fs $HOME/.yarn/bin/yarn $HOME/bin/yarn
+    yarn --version
     yarn --ignore-scripts
   post_build: npm run semantic-release
 
